version: "3.9"

services:
  api:
    build: .
    container_name: api_resumidor
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1